# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SyncMap-Draft',
                'doc_host': 'https://Loccret.github.io',
                'git_url': 'https://github.com/Loccret/SyncMap-Draft',
                'lib_path': 'SyncMap_Draft'},
  'syms': { 'SyncMap_Draft.core': {'SyncMap_Draft.core.foo': ('core.html#foo', 'SyncMap_Draft/core.py')},
            'SyncMap_Draft.utility': {'SyncMap_Draft.utility.to_categorical': ('utility.html#to_categorical', 'SyncMap_Draft/utility.py')}}}
