# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/98_NbdevExerise.ipynb.

# %% auto 0
__all__ = ['Number', 'add_a_number', 'func']

# %% ../nbs/98_NbdevExerise.ipynb 2
import fastcore.basics as fc
# from fastcore.basics import *
from nbdev.showdoc import *
# from fastcore.utils import *

# %% ../nbs/98_NbdevExerise.ipynb 4
class Number:
    "A number."
    def __init__(self, num): self.num = num
    def __repr__(self): return f'Number({self.num})'

# %% ../nbs/98_NbdevExerise.ipynb 7
@fc.patch
def add_a_number(self:Number, other):
    "Sum of this and `other`."
    return Number(self.num + other.num)

# %% ../nbs/98_NbdevExerise.ipynb 10
class _T8(int): pass  

# %% ../nbs/98_NbdevExerise.ipynb 11
@fc.patch
def func(self:_T8, a): return self+a
