name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    # steps: [uses: fastai/workflows/quarto-ghp@master]
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pytorch-main
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install dependencies
        run: |
          conda env update --file environment.yml
          conda info --envs

      - name: Deploy to GitHub Pages
        uses: fastai/workflows/quarto-ghp@master
