name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps: [uses: fastai/workflows/quarto-ghp@master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
    # - name: Install dependencies
    #   run: |
    #     pip install scikit-learn
    - uses: fastai/workflows/quarto-ghp@master

# - name: Install dependencies
#   run: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt  # Make sure to have this file or specify your project's dependencies here.